import pool from "../../database/pool.js";

type RowDataPacket = Record<string, any>;

export async function listDormCommunity(userID: number, dormID: number) {
  const [dormRows]: [RowDataPacket[], any] = await pool.query(
    "SELECT address, floor FROM dorms WHERE dormID = ?",
    [dormID]
  );
  if (!dormRows[0]) throw new Error("Dorm not found.");

  const [residents]: [RowDataPacket[], any] = await pool.query(
    `SELECT u.userID, u.username, u.roomID, COALESCE(rp.bio, '') AS bio,
            rp.updatedAt, (cb.blockerUserID IS NOT NULL) AS isBlocked
     FROM users u
     LEFT JOIN residentProfiles rp ON rp.userID = u.userID
     LEFT JOIN chatBlocks cb ON cb.blockerUserID = ? AND cb.blockedUserID = u.userID
     WHERE u.dormID = ?
       AND u.role = 'STUDENT'
       AND u.active = TRUE
       AND u.username IS NOT NULL
       AND u.mustChangePassword = FALSE
     ORDER BY u.roomID ASC, LOWER(u.username) ASC`,
    [userID, dormID]
  );

  return {
    dorm: dormRows[0],
    currentUserID: userID,
    residents: residents.map(resident => ({ ...resident, isCurrentUser: resident.userID === userID })),
  };
}

export async function updateResidentProfile(userID: number, dormID: number, bio: string) {
  const [eligible]: [RowDataPacket[], any] = await pool.query(
    `SELECT userID FROM users
     WHERE userID = ? AND dormID = ? AND role = 'STUDENT' AND active = TRUE`,
    [userID, dormID]
  );
  if (!eligible[0]) throw new Error("Resident account not found.");

  await pool.query(
    `INSERT INTO residentProfiles (userID, bio, updatedAt)
     VALUES (?, ?, CURRENT_TIMESTAMP)
     ON CONFLICT (userID) DO UPDATE
     SET bio = EXCLUDED.bio, updatedAt = CURRENT_TIMESTAMP`,
    [userID, bio]
  );
  return { bio };
}

type TaskDraft = { title: string; description: string; isImportant: boolean };
let governanceSchemaReady: Promise<void> | null = null;

export function ensureCommunityGovernanceSchema() {
  if (!governanceSchemaReady) governanceSchemaReady = (async () => {
    await pool.query(`ALTER TABLE cleaningTaskTemplate ADD COLUMN IF NOT EXISTS dormID integer REFERENCES dorms(dormID) ON DELETE CASCADE`);
    await pool.query(`CREATE TABLE IF NOT EXISTS cleaningTaskProposals (
      proposalID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      dormID integer NOT NULL REFERENCES dorms(dormID) ON DELETE CASCADE,
      proposalType varchar(10) NOT NULL CHECK (proposalType IN ('add','change','remove')),
      targetTemplateID integer REFERENCES cleaningTaskTemplate(templateID) ON DELETE CASCADE,
      proposedTitle varchar(100), proposedDescription text, proposedIsImportant boolean,
      creatorUserID integer NOT NULL REFERENCES users(userID) ON DELETE CASCADE,
      status varchar(12) NOT NULL DEFAULT 'open' CHECK (status IN ('open','approved','rejected')),
      createdAt timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, resolvedAt timestamptz,
      CHECK ((proposalType = 'add' AND targetTemplateID IS NULL) OR (proposalType <> 'add' AND targetTemplateID IS NOT NULL))
    )`);
    await pool.query(`CREATE UNIQUE INDEX IF NOT EXISTS one_open_task_action ON cleaningTaskProposals (dormID, targetTemplateID, proposalType) WHERE status = 'open'`);
    await pool.query(`CREATE TABLE IF NOT EXISTS cleaningTaskProposalVotes (
      proposalID integer NOT NULL REFERENCES cleaningTaskProposals(proposalID) ON DELETE CASCADE,
      userID integer NOT NULL REFERENCES users(userID) ON DELETE CASCADE,
      choice varchar(10) NOT NULL CHECK (choice IN ('approve','reject')),
      createdAt timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (proposalID, userID)
    )`);
  })().catch(error => { governanceSchemaReady = null; throw error; });
  return governanceSchemaReady;
}

const eligibleResidentSql = `role = 'STUDENT' AND active = TRUE AND mustChangePassword = FALSE`;

export async function listDormTaskGovernance(userID: number, dormID: number) {
  await ensureCommunityGovernanceSchema();
  const [tasks] = await pool.query(
    `SELECT ctt.templateID, ctt.taskName AS title, COALESCE(ctt.description, '') AS description,
            ctt.isImportant, ctt.createdByUserID, creator.username AS creatorUsername
     FROM cleaningTaskTemplate ctt LEFT JOIN users creator ON creator.userID = ctt.createdByUserID
     WHERE ctt.active = TRUE AND ctt.createdByUserID IS NOT NULL AND (ctt.dormID = ? OR (ctt.dormID IS NULL AND creator.dormID = ?))
     ORDER BY LOWER(ctt.taskName)`, [dormID, dormID]);
  const [proposals] = await pool.query(
    `SELECT p.proposalID, p.proposalType, p.targetTemplateID, p.proposedTitle,
            COALESCE(p.proposedDescription, '') AS proposedDescription, p.proposedIsImportant,
            p.creatorUserID, creator.username AS creatorUsername, p.status, p.createdAt, p.resolvedAt,
            target.taskName AS title, COALESCE(target.description, '') AS description, target.isImportant,
            (SELECT COUNT(*)::int FROM users u WHERE u.dormID = p.dormID AND ${eligibleResidentSql}) AS eligibleVoters,
            COUNT(v.userID) FILTER (WHERE v.choice = 'approve')::int AS approveCount,
            COUNT(v.userID) FILTER (WHERE v.choice = 'reject')::int AS rejectCount,
            MAX(v.choice) FILTER (WHERE v.userID = ?) AS currentUserVote
     FROM cleaningTaskProposals p
     JOIN users creator ON creator.userID = p.creatorUserID
     LEFT JOIN cleaningTaskTemplate target ON target.templateID = p.targetTemplateID
     LEFT JOIN cleaningTaskProposalVotes v ON v.proposalID = p.proposalID
     WHERE p.dormID = ?
     GROUP BY p.proposalID, creator.username, target.taskName, target.description, target.isImportant
     ORDER BY (p.status = 'open') DESC, p.createdAt DESC LIMIT 50`, [userID, dormID]);
  return { tasks, proposals };
}

async function assertResident(userID: number, dormID: number) {
  const [rows] = await pool.query(`SELECT userID FROM users WHERE userID = ? AND dormID = ? AND ${eligibleResidentSql}`, [userID, dormID]);
  if (!(rows as any[])[0]) throw new Error("Only active residents can take part in task votes.");
}

async function createProposal(userID: number, dormID: number, type: 'add'|'change'|'remove', targetTemplateID: number | null, draft?: TaskDraft) {
  await ensureCommunityGovernanceSchema(); await assertResident(userID, dormID);
  if (targetTemplateID) {
    const [targets] = await pool.query(`SELECT ctt.templateID FROM cleaningTaskTemplate ctt LEFT JOIN users creator ON creator.userID = ctt.createdByUserID WHERE ctt.templateID = ? AND ctt.active = TRUE AND ctt.createdByUserID IS NOT NULL AND (ctt.dormID = ? OR (ctt.dormID IS NULL AND creator.dormID = ?))`, [targetTemplateID, dormID, dormID]);
    if (!(targets as any[])[0]) throw new Error("That user-created task is not available in your dorm.");
  }
  try {
    const [rows] = await pool.query(`INSERT INTO cleaningTaskProposals (dormID, proposalType, targetTemplateID, proposedTitle, proposedDescription, proposedIsImportant, creatorUserID) VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING proposalID`, [dormID, type, targetTemplateID, draft?.title ?? null, draft?.description ?? null, draft?.isImportant ?? null, userID]);
    const proposalID = (rows as any[])[0].proposalID;
    await pool.query(`INSERT INTO cleaningTaskProposalVotes (proposalID, userID, choice) VALUES (?, ?, 'approve')`, [proposalID, userID]);
    await resolveProposal(proposalID, dormID);
    return { proposalID };
  } catch (error: any) {
    if (error?.message?.includes("one_open_task_action")) throw new Error(`There is already an open ${type} vote for this task.`);
    throw error;
  }
}

export const createTaskProposal = (userID: number, dormID: number, draft: TaskDraft) => createProposal(userID, dormID, 'add', null, draft);
export const createTaskChangeProposal = (userID: number, dormID: number, templateID: number, draft: TaskDraft) => createProposal(userID, dormID, 'change', templateID, draft);
export const createTaskRemovalProposal = (userID: number, dormID: number, templateID: number) => createProposal(userID, dormID, 'remove', templateID);

export async function cancelTaskProposal(userID: number, dormID: number, proposalID: number) {
  await ensureCommunityGovernanceSchema(); await assertResident(userID, dormID);
  const [, result]: any = await pool.query(
    `DELETE FROM cleaningTaskProposals
     WHERE proposalID = ? AND dormID = ? AND creatorUserID = ? AND status = 'open'`,
    [proposalID, dormID, userID]
  );
  if (result.affectedRows === 0) {
    const [rows] = await pool.query(`SELECT creatorUserID, status FROM cleaningTaskProposals WHERE proposalID = ? AND dormID = ?`, [proposalID, dormID]);
    const proposal: any = (rows as any[])[0];
    if (!proposal) throw new Error("This vote no longer exists.");
    if (Number(proposal.creatorUserID) !== userID) throw new Error("Only the resident who started this vote can cancel it.");
    throw new Error("This vote has already closed and cannot be cancelled.");
  }
  return { cancelled: true };
}

export async function castTaskProposalVote(userID: number, dormID: number, proposalID: number, choice: 'approve'|'reject') {
  await ensureCommunityGovernanceSchema(); await assertResident(userID, dormID);
  const [rows] = await pool.query(`SELECT proposalID FROM cleaningTaskProposals WHERE proposalID = ? AND dormID = ? AND status = 'open'`, [proposalID, dormID]);
  if (!(rows as any[])[0]) throw new Error("This vote is no longer open.");
  await pool.query(`INSERT INTO cleaningTaskProposalVotes (proposalID, userID, choice) VALUES (?, ?, ?) ON CONFLICT (proposalID, userID) DO UPDATE SET choice = EXCLUDED.choice, createdAt = CURRENT_TIMESTAMP`, [proposalID, userID, choice]);
  return resolveProposal(proposalID, dormID);
}

async function resolveProposal(proposalID: number, dormID: number) {
  const [rows] = await pool.query(`SELECT p.*, (SELECT COUNT(*)::int FROM users WHERE dormID = p.dormID AND ${eligibleResidentSql}) AS eligibleVoters, COUNT(v.userID) FILTER (WHERE v.choice='approve')::int AS approveCount, COUNT(v.userID) FILTER (WHERE v.choice='reject')::int AS rejectCount FROM cleaningTaskProposals p LEFT JOIN cleaningTaskProposalVotes v ON v.proposalID=p.proposalID WHERE p.proposalID=? AND p.dormID=? GROUP BY p.proposalID`, [proposalID, dormID]);
  const proposal: any = (rows as any[])[0]; if (!proposal || proposal.status !== 'open') return { status: proposal?.status };
  const majority = Math.floor(Number(proposal.eligibleVoters) / 2) + 1;
  let status: 'open'|'approved'|'rejected' = 'open';
  if (Number(proposal.approveCount) >= majority) status = 'approved';
  else if (Number(proposal.rejectCount) >= majority || Number(proposal.rejectCount) > Number(proposal.eligibleVoters) - majority) status = 'rejected';
  if (status === 'open') return { status, majority };
  const connection = await pool.getConnection();
  try {
    await connection.beginTransaction();
    await connection.query(`UPDATE cleaningTaskProposals SET status=?, resolvedAt=NOW() WHERE proposalID=? AND status='open'`, [status, proposalID]);
    if (status === 'approved' && proposal.proposalType === 'add') {
      const [createdRows] = await connection.query(`INSERT INTO cleaningTaskTemplate (taskName, description, active, createdByUserID, isImportant, dormID) VALUES (?, ?, TRUE, ?, ?, ?) RETURNING templateID`, [proposal.proposedTitle, proposal.proposedDescription, proposal.creatorUserID, proposal.proposedIsImportant, dormID]);
      const templateID = Number((createdRows as any[])[0]?.templateID);
      if (!Number.isInteger(templateID) || templateID <= 0) throw new Error("Database did not return the approved cleaning task ID.");
      await connection.query(`INSERT INTO cleaningAssignments (weekID, templateID, completed, assignedUserID) SELECT weekID, ?, FALSE, assignedUserID FROM cleaningWeeks WHERE dormID=? AND endDate >= CURRENT_DATE ON CONFLICT DO NOTHING`, [templateID, dormID]);
    } else if (status === 'approved' && proposal.proposalType === 'change') {
      await connection.query(`UPDATE cleaningTaskTemplate SET taskName=?, description=?, isImportant=? WHERE templateID=?`, [proposal.proposedTitle, proposal.proposedDescription, proposal.proposedIsImportant, proposal.targetTemplateID]);
    } else if (status === 'approved' && proposal.proposalType === 'remove') {
      await connection.query(`UPDATE cleaningTaskTemplate SET active=FALSE WHERE templateID=?`, [proposal.targetTemplateID]);
      await connection.query(`DELETE FROM cleaningAssignments ca USING cleaningWeeks cw WHERE ca.weekID=cw.weekID AND ca.templateID=? AND cw.dormID=? AND cw.endDate >= CURRENT_DATE AND ca.completed=FALSE`, [proposal.targetTemplateID, dormID]);
    }
    await connection.commit();
  } catch (error) { await connection.rollback(); throw error; } finally { connection.release(); }
  return { status, majority };
}
