-- Complete StudentV PostgreSQL schema. This is the only schema source of truth.
-- Example: createdb dorms_db && psql -d dorms_db -f generate-postgres.sql

CREATE TABLE dorms (
  dormid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  floor integer NOT NULL,
  address varchar(255) NOT NULL CHECK (address ~ '^[0-9]+$'),
  UNIQUE (address, floor)
);

CREATE TABLE room (
  roomid integer GENERATED BY DEFAULT AS IDENTITY,
  dormid integer NOT NULL REFERENCES dorms(dormid) ON DELETE CASCADE,
  PRIMARY KEY (roomid, dormid)
);

CREATE TABLE users (
  userid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) NOT NULL UNIQUE,
  username varchar(50) UNIQUE,
  passwordhash varchar(255) NOT NULL,
  role varchar(50) NOT NULL,
  -- Global administrators have no physical dorm or room assignment.
  roomid integer,
  dormid integer,
  active boolean NOT NULL DEFAULT true,
  scheduleddeactivationat timestamptz,
  mustchangepassword boolean NOT NULL DEFAULT false,
  credentialversion integer NOT NULL DEFAULT 0,
  CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'RESEARCHER', 'STUDENT')),
  CONSTRAINT users_room_assignment_check CHECK (
    (role IN ('ADMIN', 'RESEARCHER') AND roomid IS NULL AND dormid IS NULL) OR
    (role = 'STUDENT' AND roomid IS NOT NULL AND dormid IS NOT NULL)
  ),
  FOREIGN KEY (roomid, dormid) REFERENCES room(roomid, dormid)
);
CREATE INDEX idx_users_scheduled_deactivation ON users (scheduleddeactivationat)
  WHERE active = true AND scheduleddeactivationat IS NOT NULL;

-- Optional public resident information is kept separate from authentication data.
-- A profile belongs to exactly one user and is removed with that account.
CREATE TABLE residentprofiles (
  userid integer PRIMARY KEY REFERENCES users(userid) ON DELETE CASCADE,
  bio varchar(500) NOT NULL DEFAULT '',
  updatedat timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT residentprofiles_bio_length CHECK (char_length(bio) <= 500)
);

CREATE TABLE passwordresettokens (
  tokenid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userid integer NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  tokenhash char(64) NOT NULL UNIQUE,
  expiresat timestamptz NOT NULL,
  usedat timestamptz,
  createdat timestamptz NOT NULL DEFAULT current_timestamp
);
CREATE INDEX idx_password_reset_user_created ON passwordresettokens (userid, createdat);

CREATE TABLE survey (
  eid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question varchar(500) NOT NULL,
  active boolean NOT NULL DEFAULT true,
  createdat timestamptz NOT NULL DEFAULT current_timestamp,
  expiresat timestamptz NOT NULL,
  multiplechoice boolean NOT NULL DEFAULT false,
  dormid integer REFERENCES dorms(dormid)
);
CREATE TABLE surveyoptions (
  eid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  surveyid integer NOT NULL REFERENCES survey(eid) ON DELETE CASCADE,
  optiontext varchar(500) NOT NULL
);

CREATE TABLE surveyanswers (
  answerid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  eid integer NOT NULL REFERENCES survey(eid) ON DELETE CASCADE,
  userid integer NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  answer varchar(1000) NULL,
  answeredat timestamptz NOT NULL DEFAULT current_timestamp,

  UNIQUE (eid, userid)
);

CREATE TABLE surveyansweroptions (
  answerid integer NOT NULL
    REFERENCES surveyanswers(answerid)
    ON DELETE CASCADE,

  optionid integer NOT NULL
    REFERENCES surveyoptions(eid)
    ON DELETE CASCADE,

  PRIMARY KEY (answerid, optionid)
);

CREATE TABLE events (
  eventid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(255) NOT NULL,
  description text NOT NULL,
  startdate timestamptz NOT NULL,
  enddate timestamptz NOT NULL,
  createdat timestamptz NOT NULL DEFAULT current_timestamp,
  active boolean NOT NULL DEFAULT true,
  type varchar(100) NOT NULL,
  dormid integer NOT NULL REFERENCES dorms(dormid) ON DELETE CASCADE,
  createdbyuserid integer REFERENCES users(userid) ON DELETE SET NULL,
  cancelledat timestamptz
);
CREATE TABLE eventinvitations (
  eventid integer NOT NULL REFERENCES events(eventid) ON DELETE CASCADE,
  userid integer NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  status varchar(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined')),
  respondedat timestamptz,
  createdat timestamptz NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (eventid, userid)
);
CREATE TABLE activatedevents (
  eventid integer NOT NULL REFERENCES events(eventid) ON DELETE CASCADE,
  userid integer NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  PRIMARY KEY (eventid, userid)
);

CREATE TABLE sensor (
  sensorcode varchar(100) PRIMARY KEY,
  type varchar(100) NOT NULL,
  location varchar(255) NOT NULL,
  dormid integer NOT NULL REFERENCES dorms(dormid) ON DELETE CASCADE
);
CREATE TABLE chat (
  chatid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  createdat timestamptz NOT NULL DEFAULT current_timestamp,
  dormid integer NOT NULL REFERENCES dorms(dormid) ON DELETE CASCADE
);
CREATE TABLE chatmembers (
  chatid integer NOT NULL REFERENCES chat(chatid) ON DELETE CASCADE,
  userid integer NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  joinedat timestamptz NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (chatid, userid)
);
CREATE TABLE chatdirectconversations (
  chatid integer PRIMARY KEY REFERENCES chat(chatid) ON DELETE CASCADE,
  user1id integer NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  user2id integer NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  CHECK (user1id < user2id),
  UNIQUE (user1id, user2id)
);
CREATE TABLE chatblocks (
  blockeruserid integer NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  blockeduserid integer NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  createdat timestamptz NOT NULL DEFAULT current_timestamp,
  CHECK (blockeruserid <> blockeduserid),
  PRIMARY KEY (blockeruserid, blockeduserid)
);
CREATE TABLE chatreadstate (
  chatid integer NOT NULL REFERENCES chat(chatid) ON DELETE CASCADE,
  userid integer NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  lastreadmessageid integer NOT NULL DEFAULT 0,
  updatedat timestamptz NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (chatid, userid)
);
CREATE TABLE chathistory (
  messageid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  msg text NOT NULL,
  sentat timestamptz NOT NULL DEFAULT current_timestamp,
  chatid integer NOT NULL,
  userid integer NOT NULL,
  FOREIGN KEY (chatid, userid) REFERENCES chatmembers(chatid, userid) ON DELETE CASCADE
);
CREATE TABLE chatmessagereactions (
  messageid integer NOT NULL
      REFERENCES chathistory(messageid) ON DELETE CASCADE,
  userid integer NOT NULL
      REFERENCES users(userid) ON DELETE CASCADE,
  emoji text NOT NULL,
  createdat timestamptz NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (messageid, userid, emoji)
);
CREATE TABLE sensor_data (
  sensorcode varchar(100) NOT NULL REFERENCES sensor(sensorcode) ON DELETE CASCADE,
  recordedat timestamptz NOT NULL DEFAULT current_timestamp,
  totalvolume real NOT NULL, tempmin real NOT NULL, tempmax real NOT NULL,
  errorcode integer NOT NULL, battery real NOT NULL, ambienttemp real NOT NULL,
  humidity real NOT NULL, leakstatus boolean NOT NULL,
  PRIMARY KEY (sensorcode, recordedat)
);
CREATE TABLE sensor_notes (
  sensorcode varchar(100) PRIMARY KEY REFERENCES sensor(sensorcode) ON DELETE CASCADE,
  note text NOT NULL DEFAULT '',
  updatedat timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT sensor_notes_length CHECK (char_length(note) <= 2000)
);

CREATE TABLE cleaningtasktemplate (
  templateid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  taskname varchar(100) NOT NULL,
  description text,
  active boolean NOT NULL DEFAULT true,
  createdbyuserid integer REFERENCES users(userid) ON DELETE SET NULL,
  isimportant boolean NOT NULL DEFAULT false,
  dormid integer REFERENCES dorms(dormid) ON DELETE CASCADE
);
CREATE TABLE cleaningtaskproposals (
  proposalid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dormid integer NOT NULL REFERENCES dorms(dormid) ON DELETE CASCADE,
  proposaltype varchar(10) NOT NULL CHECK (proposaltype IN ('add','change','remove')),
  targettemplateid integer REFERENCES cleaningtasktemplate(templateid) ON DELETE CASCADE,
  proposedtitle varchar(100), proposeddescription text, proposedisimportant boolean,
  creatoruserid integer NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  status varchar(12) NOT NULL DEFAULT 'open' CHECK (status IN ('open','approved','rejected')),
  createdat timestamptz NOT NULL DEFAULT current_timestamp, resolvedat timestamptz,
  CHECK ((proposaltype = 'add' AND targettemplateid IS NULL) OR (proposaltype <> 'add' AND targettemplateid IS NOT NULL))
);
CREATE UNIQUE INDEX one_open_task_action ON cleaningtaskproposals (dormid, targettemplateid, proposaltype) WHERE status = 'open';
CREATE TABLE cleaningtaskproposalvotes (
  proposalid integer NOT NULL REFERENCES cleaningtaskproposals(proposalid) ON DELETE CASCADE,
  userid integer NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  choice varchar(10) NOT NULL CHECK (choice IN ('approve','reject')),
  createdat timestamptz NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (proposalid, userid)
);
CREATE TABLE cleaningweeks (
  weekid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dormid integer NOT NULL REFERENCES dorms(dormid) ON DELETE CASCADE,
  assigneduserid integer NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  startdate date NOT NULL, enddate date NOT NULL,
  UNIQUE (dormid, startdate), CHECK (enddate >= startdate)
);
CREATE TABLE cleaningassignments (
  assignmentid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  weekid integer NOT NULL REFERENCES cleaningweeks(weekid) ON DELETE CASCADE,
  templateid integer NOT NULL REFERENCES cleaningtasktemplate(templateid),
  completed boolean NOT NULL DEFAULT false, completedat timestamptz,
  createdat timestamptz NOT NULL DEFAULT current_timestamp,
  assigneduserid integer REFERENCES users(userid) ON DELETE SET NULL,
  UNIQUE (weekid, templateid)
);

CREATE TABLE cleaningweekswaprequests (
  requestid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dormid integer NOT NULL REFERENCES dorms(dormid) ON DELETE CASCADE,
  requesteruserid integer NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  targetuserid integer NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  sourceweekid integer NOT NULL REFERENCES cleaningweeks(weekid) ON DELETE CASCADE,
  targetweekid integer NOT NULL REFERENCES cleaningweeks(weekid) ON DELETE CASCADE,
  status varchar(20) NOT NULL DEFAULT 'pending',
  createdat timestamptz NOT NULL DEFAULT current_timestamp,
  updatedat timestamptz NOT NULL DEFAULT current_timestamp,
  CHECK (status IN ('pending', 'accepted', 'rejected'))
);
CREATE TABLE externalevents (
    eventID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    externalURL VARCHAR(500) UNIQUE NOT NULL,
    title VARCHAR(255),
    startDate TIMESTAMPTZ,
    endDate TIMESTAMPTZ,
    createdAt TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    lastSeen TIMESTAMPTZ
);

CREATE TABLE nationsguideevents (
    eventID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    externalURL VARCHAR(500),
    title VARCHAR(255),
    startDate TIMESTAMPTZ NOT NULL,
    endDate TIMESTAMPTZ,
    category VARCHAR(100),
    organiser VARCHAR(255),
    createdAt TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Daily anonymous page-view counters. Deliberately has no user/device identifier.
CREATE TABLE page_visit_stats (
  visitdate date NOT NULL,
  page varchar(80) NOT NULL,
  visits integer NOT NULL DEFAULT 0 CHECK (visits >= 0),
  PRIMARY KEY (visitdate, page)
);
