<template>
  <section id="task-votes" class="space-y-5 rounded-3xl border border-border-border bg-background p-5 shadow-sm dark:bg-surface-dark sm:p-7">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
      <div><p class="text-xs font-bold uppercase tracking-[.14em] text-accent">{{ t('communityHub.sharedCleaning') }}</p><h2 class="mt-1 text-2xl font-extrabold">{{ t('communityHub.rotationTitle') }}</h2><p class="mt-2 max-w-2xl text-sm leading-6 opacity-65">{{ t('communityHub.rotationHelp') }}</p></div>
      <button class="shrink-0 rounded-xl bg-accent px-4 py-3 font-bold text-white" @click="showCreateForm = !showCreateForm">{{ showCreateForm ? t('communityHub.closeForm') : `+ ${t('communityHub.suggestTask')}` }}</button>
    </div>
    <form v-if="showCreateForm" class="grid gap-3 rounded-2xl bg-surface p-4 dark:bg-background-dark sm:grid-cols-2" @submit.prevent="submitNewTask">
      <label class="text-sm font-bold">{{ t('communityHub.taskName') }}<input v-model.trim="taskForm.title" required minlength="2" maxlength="100" class="mt-1 w-full p-3 font-normal" :placeholder="t('communityHub.taskPlaceholder')" /></label>
      <label class="text-sm font-bold">{{ t('communityHub.details') }}<textarea v-model.trim="taskForm.description" maxlength="1000" rows="2" class="mt-1 w-full p-3 font-normal" :placeholder="t('communityHub.detailsPlaceholder')" /></label>
      <label class="flex items-center gap-2 text-sm"><input v-model="taskForm.isImportant" type="checkbox" class="h-4 w-4" /> {{ t('communityHub.markImportant') }}</label>
      <button :disabled="savingTask || taskForm.title.length < 2" class="rounded-xl bg-accent px-4 py-3 font-bold text-white disabled:opacity-45">{{ savingTask ? t('communityHub.startingVote') : t('communityHub.startMajority') }}</button>
    </form>
    <p v-if="taskMessage" class="rounded-xl p-3 text-sm font-semibold" :class="taskFailed ? 'bg-error/10 text-error' : 'bg-success/10 text-success'" role="status">{{ taskMessage }}</p>
    <div v-if="openProposals.length" class="space-y-3">
      <div class="flex items-center justify-between"><h3 class="text-lg font-extrabold">{{ t('communityHub.openVotes') }}</h3><span class="rounded-full bg-error px-3 py-1 text-xs font-extrabold text-white">{{ t('communityHub.needAttention', { count: openProposals.length }) }}</span></div>
      <article v-for="proposal in openProposals" :key="proposal.proposalID" class="rounded-2xl border border-accent/30 bg-accent/5 p-4 sm:p-5">
        <div class="flex flex-col gap-3 sm:flex-row sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-wide text-accent">{{ proposalLabel(proposal) }}</p><h4 class="mt-1 text-lg font-extrabold">{{ proposal.proposalType === 'remove' ? proposal.title : proposal.proposedTitle }}</h4><p v-if="proposal.proposalType === 'change'" class="mt-1 text-sm opacity-60">{{ t('communityHub.currentVersion', { title: proposal.title }) }}</p><p class="mt-2 whitespace-pre-line text-sm opacity-75">{{ proposal.proposalType === 'remove' ? proposal.description : proposal.proposedDescription }}</p><p class="mt-2 text-xs opacity-55">{{ t('communityHub.suggestedBy', { name: proposal.creatorUsername }) }}</p><button v-if="proposal.creatorUserID === currentUserID" class="mt-3 text-sm font-bold text-error hover:underline" @click="cancelVote(proposal)">{{ t('communityHub.cancelVote') }}</button></div><div class="shrink-0 sm:w-56"><p class="text-sm font-bold">{{ t('communityHub.voteCounts', { approve: proposal.approveCount, reject: proposal.rejectCount }) }}</p><div class="mt-2 h-2 overflow-hidden rounded-full bg-black/10"><div class="h-full bg-accent" :style="{ width: `${Math.min(100, proposal.approveCount / proposal.majority * 100)}%` }"></div></div><p class="mt-1 text-xs opacity-55">{{ t('communityHub.approvalsNeeded', { count: proposal.majority }) }}</p><div class="mt-3 grid grid-cols-2 gap-2"><button class="rounded-lg px-3 py-2 text-sm font-bold" :class="proposal.currentUserVote === 'approve' ? 'bg-success text-white' : 'border border-success text-success'" @click="vote(proposal, 'approve')">{{ t(proposal.proposalType === 'change' ? 'communityHub.newVersion' : 'communityHub.approve') }}</button><button class="rounded-lg px-3 py-2 text-sm font-bold" :class="proposal.currentUserVote === 'reject' ? 'bg-error text-white' : 'border border-error text-error'" @click="vote(proposal, 'reject')">{{ t(proposal.proposalType === 'change' ? 'communityHub.keepCurrent' : 'communityHub.reject') }}</button></div></div></div>
      </article>
    </div>
    <div v-else class="rounded-2xl border border-dashed border-border-border p-6 text-center"><h3 class="font-bold">{{ t('communityHub.noVotes') }}</h3><p class="mt-1 text-sm opacity-60">{{ t('communityHub.settled') }}</p></div>
    <div><h3 class="text-lg font-extrabold">{{ t('communityHub.residentTasks') }}</h3><div v-if="tasks.length" class="mt-3 grid gap-3 md:grid-cols-2"><article v-for="task in tasks" :key="task.templateID" class="rounded-2xl border border-border-border p-4"><div class="flex items-start justify-between gap-3"><div><h4 class="font-extrabold">{{ task.title }}</h4><p class="mt-1 text-sm opacity-65">{{ task.description || t('communityHub.noInstructions') }}</p><p class="mt-2 text-xs opacity-50">{{ t('communityHub.addedBy', { name: task.creatorUsername }) }}</p></div><span v-if="task.isImportant" class="rounded-full bg-error/10 px-2 py-1 text-xs font-bold text-error">{{ t('communityHub.important') }}</span></div><div class="mt-4 flex gap-2"><button class="rounded-lg border border-border-border px-3 py-2 text-sm font-bold" @click="beginChange(task)">{{ t('communityHub.suggestChange') }}</button><button class="rounded-lg border border-error/40 px-3 py-2 text-sm font-bold text-error" @click="startRemoval(task)">{{ t('communityHub.voteRemove') }}</button></div></article></div><p v-else class="mt-3 text-sm opacity-60">{{ t('communityHub.noApprovedTasks') }}</p></div>
    <form v-if="editingTask" class="grid gap-3 rounded-2xl border border-accent/30 p-4 sm:grid-cols-2" @submit.prevent="submitChange"><div class="sm:col-span-2"><p class="font-extrabold">{{ t('communityHub.suggestVersion', { title: editingTask.title }) }}</p><p class="text-sm opacity-60">{{ t('communityHub.versionHelp') }}</p></div><input v-model.trim="editForm.title" required maxlength="100" class="p-3" /><textarea v-model.trim="editForm.description" maxlength="1000" rows="2" class="p-3" /><label class="flex items-center gap-2 text-sm"><input v-model="editForm.isImportant" type="checkbox" /> {{ t('communityHub.important') }}</label><div class="flex gap-2"><button type="button" class="flex-1 rounded-xl border px-3 py-2 font-bold" @click="editingTask = null">{{ t('common.cancel') }}</button><button class="flex-1 rounded-xl bg-accent px-3 py-2 font-bold text-white">{{ t('communityHub.startVote') }}</button></div></form>
  </section>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { apiUrl } from '@/shared/composables/api'
import { getSocket } from '@/shared/composables/socket'
import { useI18n } from 'vue-i18n'

type RotationTask = { templateID: number; title: string; description: string; isImportant: boolean; creatorUsername: string }
type TaskProposal = { proposalID: number; proposalType: 'add'|'change'|'remove'; targetTemplateID: number|null; proposedTitle:string|null; proposedDescription:string; proposedIsImportant:boolean|null; creatorUserID:number; creatorUsername:string; status:string; title:string|null; description:string; approveCount:number; rejectCount:number; eligibleVoters:number; currentUserVote:'approve'|'reject'|null; majority:number }
const { t } = useI18n(), socket = getSocket()
const currentUserID = Number(sessionStorage.getItem('userID') || 0)
const tasks = ref<RotationTask[]>([]), proposals = ref<TaskProposal[]>([])
const showCreateForm = ref(false), savingTask = ref(false), taskMessage = ref(''), taskFailed = ref(false)
const taskForm = reactive({ title: '', description: '', isImportant: false })
const editingTask = ref<RotationTask|null>(null), editForm = reactive({ title: '', description: '', isImportant: false })
const openProposals = computed(() => proposals.value.filter(p => p.status === 'open').map(p => ({ ...p, majority: Math.floor(Number(p.eligibleVoters) / 2) + 1 })))
const headers = () => ({ 'Content-Type': 'application/json', Authorization: `Bearer ${sessionStorage.getItem('authToken') || ''}` })
async function request(path: string, options: RequestInit = {}) { const response = await fetch(apiUrl(path), { ...options, headers: headers() }); const data = await response.json(); if (!response.ok) throw new Error(data.error || t('communityHub.tasksError')); return data }
async function load() { try { const data = await request('/api/community/cleaning-tasks'); tasks.value = data.tasks; proposals.value = data.proposals } catch (error) { taskFailed.value = true; taskMessage.value = error instanceof Error ? error.message : t('communityHub.votesError') } }
async function perform(action: () => Promise<unknown>, success: string) { savingTask.value = true; taskMessage.value = ''; try { await action(); taskFailed.value = false; taskMessage.value = success; await load() } catch (error) { taskFailed.value = true; taskMessage.value = error instanceof Error ? error.message : t('communityHub.genericError') } finally { savingTask.value = false } }
async function submitNewTask() { await perform(() => request('/api/community/cleaning-tasks/proposals', { method: 'POST', body: JSON.stringify(taskForm) }), t('communityHub.proposalOpen')); if (!taskFailed.value) { Object.assign(taskForm, { title: '', description: '', isImportant: false }); showCreateForm.value = false } }
function beginChange(task: RotationTask) { editingTask.value = task; Object.assign(editForm, { title: task.title, description: task.description, isImportant: task.isImportant }); requestAnimationFrame(() => document.getElementById('task-votes')?.scrollIntoView({ behavior: 'smooth' })) }
async function submitChange() { if (!editingTask.value) return; await perform(() => request(`/api/community/cleaning-tasks/${editingTask.value!.templateID}/change`, { method: 'POST', body: JSON.stringify(editForm) }), t('communityHub.changeOpen')); if (!taskFailed.value) editingTask.value = null }
async function startRemoval(task: RotationTask) { await perform(() => request(`/api/community/cleaning-tasks/${task.templateID}/remove`, { method: 'POST' }), t('communityHub.removalOpen', { title: task.title })) }
async function vote(proposal: TaskProposal, choice: 'approve'|'reject') { await perform(() => request(`/api/community/cleaning-tasks/proposals/${proposal.proposalID}/vote`, { method: 'POST', body: JSON.stringify({ choice }) }), t('communityHub.voteRecorded')) }
async function cancelVote(proposal: TaskProposal) { await perform(() => request(`/api/community/cleaning-tasks/proposals/${proposal.proposalID}`, { method: 'DELETE' }), t('communityHub.voteCancelled')) }
function proposalLabel(proposal: TaskProposal) { return t(proposal.proposalType === 'add' ? 'communityHub.addRotation' : proposal.proposalType === 'remove' ? 'communityHub.removeRotation' : 'communityHub.chooseVersion') }
onMounted(() => { void load(); socket.on('cleaningTaskProposalsUpdated', load) })
onBeforeUnmount(() => socket.off('cleaningTaskProposalsUpdated', load))
</script>
